import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import githubLogo from "../public/logo-github.png";
import linkedinLogo from "../public/logo-linkedin.png";

export default function Home() {
  return (
    <div className="h-screen w-screen grid grid-rows-layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between items-center px-3">
        <div className="font-bold">献一　沖胡</div>
        <div className="">theme trigger</div>
      </header>
      <main className="px-3">
        <div className="py-2">
          <h3 className="font-bold text-xl">ケン　オキエビス</h3>
        </div>
        <h3 className="font-bold text-4xl">Ken Okiebisu</h3>
        <div className="py-8">
          <h4 className="font-bold text-lg">
            Software Engineer. Based in Vancouver, Canada
          </h4>
        </div>
        <div className="md:flex py-12">
          {/* <div className="w-full">
            <h3 className="font-bold text-3xl">Projects</h3>
            <div></div>
          </div>
          <div className="w-full">
            <h3 className="font-bold text-3xl">Background</h3>
            <div></div>
          </div> */}
        </div>
      </main>
      <footer className="">
        <div className="flex justify-center items-center py-6">
          <div className="mx-2">
            <Link href="https://github.com/kokiebisu">
              <Image
                src={githubLogo}
                width={25}
                height={25}
                alt="Github Icon"
              />
            </Link>
          </div>
          <div className="mx-2">
            <Link href="https://github.com/kokiebisu">
              <Image
                src={linkedinLogo}
                width={25}
                height={25}
                alt="LinkedIn Icon"
              />
            </Link>
          </div>
        </div>
        <div className="px-3 flex justify-between items-center">
          <div>
            <span className="mx-3 font-bold">ABOUT</span>
            <span className="mx-3 font-bold">PROJECTS</span>
            <span className="mx-3 font-bold">BACKGROUND</span>
          </div>
          <div className="mx-3 font-bold">ver.2022</div>
        </div>
      </footer>
    </div>
  );
}
