import Head from "next/head";

export default function Home() {
  return (
    <div className="h-screen w-screen bg-black grid grid-rows-layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="text-red-300 bg-blue-300 flex justify-between items-center px-3">
        <div className="">kokiebisu</div>
        <div className="">theme trigger</div>
      </header>
      <main className="px-3">
        <h1 className="text-red-300">Hello world!</h1>
      </main>

      <footer className=" bg-red-500"></footer>
    </div>
  );
}
